from app.schemas.auth import (
    AuthResponse,
    ChangePassword,
    ForgotPassword,
    LoginRequest,
    OTPSend,
    RegisterHospitalStaff,
    RegisterPatient,
    RefreshRequest,
    ResetPassword,
    TokenPair,
    VerifyOTP,
)
from app.schemas.user import (
    DoctorAvailability,
    DoctorDetail,
    DoctorOut,
    DoctorUpdate,
    FamilyMember,
    PatientOut,
    PatientUpdate,
    UserOut,
    UserUpdate,
)
from app.schemas.hospital import (
    CityCreate,
    CityOut,
    DepartmentCreate,
    DepartmentOut,
    DepartmentUpdate,
    HospitalCompareOut,
    HospitalCreate,
    HospitalOut,
    HospitalUpdate,
)
from app.schemas.clinical import (
    AppointmentCreate,
    AppointmentOut,
    AppointmentUpdate,
    EmergencyCreate,
    EmergencyOut,
    FeedbackCreate,
    FeedbackOut,
    LabBookingCreate,
    MedicationReminderCreate,
    MedicalRecordCreate,
    MedicalRecordOut,
    PrescriptionOut,
    TokenCreate,
    TokenOut,
    TokenStatus,
    TransferRequest,
)
from app.schemas.misc import (
    AnalyticsOut,
    ApiResponse,
    AuditLogOut,
    CrowdPredictionResult,
    NoShowRequest,
    NoShowResult,
    NotificationOut,
    QueueOut,
    RecommendationRequest,
    SearchResults,
    SentimentRequest,
    SentimentResult,
    SettingsOut,
    TriageRequest,
    TriageResult,
    WaitPredictionRequest,
    WaitPredictionResult,
    WorkloadResult,
)

__all__ = [name for name in globals() if name.isupper() or name in locals()]
